services:
  radiometerwebapp:
    image: cr.yandex/crpfcpvoap78esunmram/radiometer
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/fullchain.pem"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/https/privkey.pem"
    volumes:
      - ./conf.d/https/:/https/